[profile.default]
solc_version = "0.8.29"
evm_version = "cancun"

optimizer = true
optimizer_runs = 9_999_999

via_ir = true

remappings = [
  "@solady=lib/solady/",
  "@soledge=lib/soledge/",
  "@forge=lib/forge-std/src/"
]

[profile.via-ir]
via_ir = true

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://eth.llamarpc.com"
base = "https://rpc.ankr.com/base"
poly = "https://rpc.ankr.com/polygon"
opti = "https://rpc.ankr.com/optimism"
arbi = "https://rpc.ankr.com/arbitrum"